//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models.Agency
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsuranceCase
    {
        public int id { get; set; }
        public string contract { get; set; }
        public string description { get; set; }
        public int insurant { get; set; }
        public string phone { get; set; }
        public int status { get; set; }
        public System.DateTime datestart { get; set; }
        public Nullable<System.DateTime> datestop { get; set; }
    
        public virtual Insurant Insurant1 { get; set; }
        public virtual Status Status1 { get; set; }
    }
}
