//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models.Agency
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AgencyEntities : DbContext
    {
        public AgencyEntities()
            : base("name=AgencyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agent> Agent { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Coef> Coef { get; set; }
        public virtual DbSet<Contract> Contract { get; set; }
        public virtual DbSet<InsuranceCase> InsuranceCase { get; set; }
        public virtual DbSet<Insurant> Insurant { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Tax> Tax { get; set; }
        public virtual DbSet<Type> Type { get; set; }
    }
}
